# POST http://gosho/doors/<NAME>/open
# POST http://gosho/doors/<NAME>/lock
# POST http://gosho/doors/<NAME>/unlock
development:

  gate:
    human_name:
      en: Gate
      bg: Порта
    controller:
      klass: GoshoDoorControl
      options:
        host: 127.0.0.1
        port: 6969
        username: foo
        password: bar
    actions:
      open:
        roles:
          - board_member
          - trusted_member
          - landlord
          - tenant

  building_door:
    human_name:
      en: Building Door
      bg: Входна врата
    controller:
      klass: GoshoDoorControl
      options:
        host: 127.0.0.1
        port: 6969
        username: foo
        password: bar
    actions:
      lock:
        roles:
          - board_member
          - trusted_member
          - landlord
          - tenant
      unlock:
        roles:
          - board_member
          - trusted_member
          - landlord
          - tenant
      open:
        roles:
          - board_member
          - trusted_member
          - landlord
          - tenant

  floor_3_door:
    human_name:
      en: 3rd Floor Door
      bg: Врата 3-ти етаж
    controller:
      klass: GoshoDoorControl
      options:
        host: 127.0.0.1
        port: 6969
        username: foo
        password: bar
    actions:
      open:
        roles:
          - board_member
          - trusted_member
