space: init Lab
logo: initlab-logo.png
url: https://initlab.org
location:
  address: floor 3, 64A, Tsar Asen Str., Sofia, Bulgaria
  lat: 42.6879500
  lon: 23.3169100
spacefed:
  spacenet: false
  spacesaml: false
  spacephone: false
contact:
  irc: irc://irc.ludost.net/#initlab
  twitter: '@initLab'
  ml: yo@initlab.org
  issue_mail: us@initlab.org
issue_report_channels:
  - issue_mail
feeds:
  blog:
    type: rss
    url: https://initlab.org/feed/
  wiki:
    type: atom
    url: https://wiki.initlab.org/api.php?hidebots=1&days=7&limit=50&action=feedrecentchanges&feedformat=atom
  calendar:
    type: ical
    url: https://initlab.org/?ical=1
projects:
  - https://wiki.initlab.org/index.php/Category:Project
  - https://github.com/initLab/
